source 'https://github.com/CocoaPods/Specs.git'

target 'Realm-Rest', :exclusive => true do
  pod "Realm-Rest", :path => "../"
end

target 'Tests', :exclusive => true do
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'Expecta'
  pod 'OHHTTPStubs'
  pod 'OCMock'
end

